local speaker = peripheral.find("speaker")
speaker.playNote("bit")
sleep()
print("CC Tweaked BIOS")
sleep(1)
print("Copyright 2012-2022")
print("Powered by Betterboot. Made by Nexus ")
sleep(1)
print("Memory Test: 1MB")
sleep(2)
print("OK")
sleep(1)
print("Initilize Peripherals...")
sleep(2)
print("Keyboard Input")
sleep(1)
print("Mouse Input")
sleep(1)
print("Monitors")
sleep(1)
print("Speakers")
sleep(1)
print("Disk Drives")
sleep(1)
print("Printers")
sleep(2)
print("Peripherals Init Completed")
sleep(1)
shell.run("clear")

sleep(3)
print("Starting Craft OS...")
sleep(1)
print("HIMEM is testing extended memory...")
sleep(3)
print("Done!")
sleep(1)
print("Searching for Input...")
sleep(1)
print("Searching for Storage Device...")
sleep(1)
print("Searching for External Devices...")
sleep(2)
print("Initilizing Software")
sleep(3)
print("Done!")
